/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.why.srpc.core;

import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Generated;

import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

@SuppressWarnings({ "cast", "rawtypes", "serial", "unchecked" })
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-03-11")
public class Response implements org.apache.thrift.TBase<Response, Response._Fields>, java.io.Serializable, Cloneable,
		Comparable<Response> {
	private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct(
			"Response");

	private static final org.apache.thrift.protocol.TField UUID_FIELD_DESC = new org.apache.thrift.protocol.TField(
			"uuid", org.apache.thrift.protocol.TType.STRING, (short) 1);
	private static final org.apache.thrift.protocol.TField RESULT_FIELD_DESC = new org.apache.thrift.protocol.TField(
			"result", org.apache.thrift.protocol.TType.STRING, (short) 2);

	private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
	static {
		schemes.put(StandardScheme.class, new ResponseStandardSchemeFactory());
		schemes.put(TupleScheme.class, new ResponseTupleSchemeFactory());
	}

	public String uuid; // required
	public String result; // required

	/**
	 * The set of fields this struct contains, along with convenience methods
	 * for finding and manipulating them.
	 */
	public enum _Fields implements org.apache.thrift.TFieldIdEnum {
		UUID((short) 1, "uuid"), RESULT((short) 2, "result");

		private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

		static {
			for (_Fields field : EnumSet.allOf(_Fields.class)) {
				byName.put(field.getFieldName(), field);
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, or null if its not
		 * found.
		 */
		public static _Fields findByThriftId(int fieldId) {
			switch (fieldId) {
			case 1: // UUID
				return UUID;
			case 2: // RESULT
				return RESULT;
			default:
				return null;
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, throwing an exception
		 * if it is not found.
		 */
		public static _Fields findByThriftIdOrThrow(int fieldId) {
			_Fields fields = findByThriftId(fieldId);
			if (fields == null)
				throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
			return fields;
		}

		/**
		 * Find the _Fields constant that matches name, or null if its not
		 * found.
		 */
		public static _Fields findByName(String name) {
			return byName.get(name);
		}

		private final short _thriftId;
		private final String _fieldName;

		_Fields(short thriftId, String fieldName) {
			_thriftId = thriftId;
			_fieldName = fieldName;
		}

		public short getThriftFieldId() {
			return _thriftId;
		}

		public String getFieldName() {
			return _fieldName;
		}
	}

	// isset id assignments
	public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
	static {
		Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(
				_Fields.class);
		tmpMap.put(_Fields.UUID,
				new org.apache.thrift.meta_data.FieldMetaData("uuid", org.apache.thrift.TFieldRequirementType.REQUIRED,
						new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
		tmpMap.put(_Fields.RESULT,
				new org.apache.thrift.meta_data.FieldMetaData("result",
						org.apache.thrift.TFieldRequirementType.REQUIRED,
						new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
		metaDataMap = Collections.unmodifiableMap(tmpMap);
		org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Response.class, metaDataMap);
	}

	public Response() {
	}

	public Response(String uuid, String result) {
		this();
		this.uuid = uuid;
		this.result = result;
	}

	/**
	 * Performs a deep copy on <i>other</i>.
	 */
	public Response(Response other) {
		if (other.isSetUuid()) {
			this.uuid = other.uuid;
		}
		if (other.isSetResult()) {
			this.result = other.result;
		}
	}

	public Response deepCopy() {
		return new Response(this);
	}

	public void clear() {
		this.uuid = null;
		this.result = null;
	}

	public String getUuid() {
		return this.uuid;
	}

	public Response setUuid(String uuid) {
		this.uuid = uuid;
		return this;
	}

	public void unsetUuid() {
		this.uuid = null;
	}

	/**
	 * Returns true if field uuid is set (has been assigned a value) and false
	 * otherwise
	 */
	public boolean isSetUuid() {
		return this.uuid != null;
	}

	public void setUuidIsSet(boolean value) {
		if (!value) {
			this.uuid = null;
		}
	}

	public String getResult() {
		return this.result;
	}

	public Response setResult(String result) {
		this.result = result;
		return this;
	}

	public void unsetResult() {
		this.result = null;
	}

	/**
	 * Returns true if field result is set (has been assigned a value) and false
	 * otherwise
	 */
	public boolean isSetResult() {
		return this.result != null;
	}

	public void setResultIsSet(boolean value) {
		if (!value) {
			this.result = null;
		}
	}

	public void setFieldValue(_Fields field, Object value) {
		switch (field) {
		case UUID:
			if (value == null) {
				unsetUuid();
			} else {
				setUuid((String) value);
			}
			break;

		case RESULT:
			if (value == null) {
				unsetResult();
			} else {
				setResult((String) value);
			}
			break;

		}
	}

	public Object getFieldValue(_Fields field) {
		switch (field) {
		case UUID:
			return getUuid();

		case RESULT:
			return getResult();

		}
		throw new IllegalStateException();
	}

	/**
	 * Returns true if field corresponding to fieldID is set (has been assigned
	 * a value) and false otherwise
	 */
	public boolean isSet(_Fields field) {
		if (field == null) {
			throw new IllegalArgumentException();
		}

		switch (field) {
		case UUID:
			return isSetUuid();
		case RESULT:
			return isSetResult();
		}
		throw new IllegalStateException();
	}

	@Override
	public boolean equals(Object that) {
		if (that == null)
			return false;
		if (that instanceof Response)
			return this.equals((Response) that);
		return false;
	}

	public boolean equals(Response that) {
		if (that == null)
			return false;

		boolean this_present_uuid = true && this.isSetUuid();
		boolean that_present_uuid = true && that.isSetUuid();
		if (this_present_uuid || that_present_uuid) {
			if (!(this_present_uuid && that_present_uuid))
				return false;
			if (!this.uuid.equals(that.uuid))
				return false;
		}

		boolean this_present_result = true && this.isSetResult();
		boolean that_present_result = true && that.isSetResult();
		if (this_present_result || that_present_result) {
			if (!(this_present_result && that_present_result))
				return false;
			if (!this.result.equals(that.result))
				return false;
		}

		return true;
	}

	@Override
	public int hashCode() {
		List<Object> list = new ArrayList<Object>();

		boolean present_uuid = true && (isSetUuid());
		list.add(present_uuid);
		if (present_uuid)
			list.add(uuid);

		boolean present_result = true && (isSetResult());
		list.add(present_result);
		if (present_result)
			list.add(result);

		return list.hashCode();
	}

	public int compareTo(Response other) {
		if (!getClass().equals(other.getClass())) {
			return getClass().getName().compareTo(other.getClass().getName());
		}

		int lastComparison = 0;

		lastComparison = Boolean.valueOf(isSetUuid()).compareTo(other.isSetUuid());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetUuid()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.uuid, other.uuid);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetResult()).compareTo(other.isSetResult());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetResult()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.result, other.result);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		return 0;
	}

	public _Fields fieldForId(int fieldId) {
		return _Fields.findByThriftId(fieldId);
	}

	public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
		schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
	}

	public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
		schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Response(");
		boolean first = true;

		sb.append("uuid:");
		if (this.uuid == null) {
			sb.append("null");
		} else {
			sb.append(this.uuid);
		}
		first = false;
		if (!first)
			sb.append(", ");
		sb.append("result:");
		if (this.result == null) {
			sb.append("null");
		} else {
			sb.append(this.result);
		}
		first = false;
		sb.append(")");
		return sb.toString();
	}

	public void validate() throws org.apache.thrift.TException {
		// check for required fields
		if (uuid == null) {
			throw new org.apache.thrift.protocol.TProtocolException(
					"Required field 'uuid' was not present! Struct: " + toString());
		}
		if (result == null) {
			throw new org.apache.thrift.protocol.TProtocolException(
					"Required field 'result' was not present! Struct: " + toString());
		}
		// check for sub-struct validity
	}

	private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
		try {
			write(new org.apache.thrift.protocol.TCompactProtocol(
					new org.apache.thrift.transport.TIOStreamTransport(out)));
		} catch (org.apache.thrift.TException te) {
			throw new java.io.IOException(te);
		}
	}

	private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
		try {
			read(new org.apache.thrift.protocol.TCompactProtocol(
					new org.apache.thrift.transport.TIOStreamTransport(in)));
		} catch (org.apache.thrift.TException te) {
			throw new java.io.IOException(te);
		}
	}

	private static class ResponseStandardSchemeFactory implements SchemeFactory {
		public ResponseStandardScheme getScheme() {
			return new ResponseStandardScheme();
		}
	}

	private static class ResponseStandardScheme extends StandardScheme<Response> {

		public void read(org.apache.thrift.protocol.TProtocol iprot, Response struct)
				throws org.apache.thrift.TException {
			org.apache.thrift.protocol.TField schemeField;
			iprot.readStructBegin();
			while (true) {
				schemeField = iprot.readFieldBegin();
				if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
					break;
				}
				switch (schemeField.id) {
				case 1: // UUID
					if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
						struct.uuid = iprot.readString();
						struct.setUuidIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 2: // RESULT
					if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
						struct.result = iprot.readString();
						struct.setResultIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				default:
					org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
				}
				iprot.readFieldEnd();
			}
			iprot.readStructEnd();

			// check for required fields of primitive type, which can't be
			// checked in the validate method
			struct.validate();
		}

		public void write(org.apache.thrift.protocol.TProtocol oprot, Response struct)
				throws org.apache.thrift.TException {
			struct.validate();

			oprot.writeStructBegin(STRUCT_DESC);
			if (struct.uuid != null) {
				oprot.writeFieldBegin(UUID_FIELD_DESC);
				oprot.writeString(struct.uuid);
				oprot.writeFieldEnd();
			}
			if (struct.result != null) {
				oprot.writeFieldBegin(RESULT_FIELD_DESC);
				oprot.writeString(struct.result);
				oprot.writeFieldEnd();
			}
			oprot.writeFieldStop();
			oprot.writeStructEnd();
		}

	}

	private static class ResponseTupleSchemeFactory implements SchemeFactory {
		public ResponseTupleScheme getScheme() {
			return new ResponseTupleScheme();
		}
	}

	private static class ResponseTupleScheme extends TupleScheme<Response> {

		public void write(org.apache.thrift.protocol.TProtocol prot, Response struct)
				throws org.apache.thrift.TException {
			TTupleProtocol oprot = (TTupleProtocol) prot;
			oprot.writeString(struct.uuid);
			oprot.writeString(struct.result);
		}

		public void read(org.apache.thrift.protocol.TProtocol prot, Response struct)
				throws org.apache.thrift.TException {
			TTupleProtocol iprot = (TTupleProtocol) prot;
			struct.uuid = iprot.readString();
			struct.setUuidIsSet(true);
			struct.result = iprot.readString();
			struct.setResultIsSet(true);
		}
	}

}
